name: lux-browser-release
base: core22
version: '2.10'
summary: Lux Browser's release snap
description: |
  Lux Browser's Installer required snap to download Lux Browser
grade: nightly
confinement: strict
